name: ✨ 功能建议
description: 为 HiveChat 提出新功能或改进建议
title: '[Feature]: '
labels: ['feature-request', 'enhancement']
assignees:
  - wuhaoworld
  - hiratwu
body:
  - type: markdown
    attributes:
      value: |
        感谢您提出新功能建议！请尽可能详细地描述，帮助我们理解您的需求。

  - type: textarea
    id: feature-description
    attributes:
      label: 功能描述
      description: 清晰简洁地描述您希望实现的功能。
      placeholder: 描述您的功能想法...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 问题描述
      description: 这个功能解决什么问题？目前的痛点是什么？
      placeholder: 描述这个功能要解决的问题...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 解决方案
      description: 描述您希望实现的解决方案。
      placeholder: 这个功能应该如何工作？
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: 功能分类
      description: 这个功能涉及 HiveChat 的哪个方面？
      options:
        - 聊天界面
        - AI 模型集成
        - 用户管理
        - 管理面板
        - 身份验证
        - 数据库/存储
        - API/后端
        - UI/UX
        - 性能
        - 安全
        - 文档
        - 其他
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 这个功能对您有多重要？
      options:
        - 低 - 有更好
        - 中 - 会很有帮助
        - 高 - 对我的使用场景很重要
        - 紧急 - 阻碍我的使用
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 描述您考虑过的任何替代解决方案或功能。
      placeholder: 您考虑过哪些替代方案？

  - type: textarea
    id: use-cases
    attributes:
      label: 使用场景
      description: 提供此功能如何使用的具体示例。
      placeholder: |
        1. 作为用户，我想要...
        2. 当我在做 X 时，我需要...
        3. 这将有助于...

  - type: textarea
    id: user-stories
    attributes:
      label: 用户故事（可选）
      description: 如果适用，为此功能编写用户故事。
      placeholder: |
        作为 [用户类型]，我想要 [功能] 以便 [获得好处]。

  - type: textarea
    id: mockups
    attributes:
      label: 原型图/线框图
      description: 如果您有任何视觉想法，请在此分享。
      placeholder: 附加或链接到原型图、线框图或草图...

  - type: textarea
    id: additional-context
    attributes:
      label: 其他信息
      description: 添加有关功能请求的任何其他信息、截图或示例。
      placeholder: 任何其他信息...

  - type: checkboxes
    id: contribution
    attributes:
      label: 贡献
      description: 您是否有兴趣为此功能做贡献？
      options:
        - label: 我有兴趣实现这个功能
          required: false
        - label: 我可以测试这个功能
          required: false
        - label: 我愿意在开发过程中提供反馈
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 请确认以下项目
      options:
        - label: 我已搜索现有的 issues 以确保此功能之前未被请求过
          required: true
        - label: 我已提供足够详细信息供开发团队理解请求
          required: true
        - label: 此功能符合 HiveChat 作为团队导向的 AI 聊天应用程序的目标
          required: true